
# set the path-to-files
TRAIN_FILE = "/home/luban/work_jupyter/point_rec_data/train.csv.test"
TEST_FILE = "/home/luban/work_jupyter/point_rec_data/test.csv.test"

SUB_DIR = "./output"


NUM_SPLITS = 3
RANDOM_SEED = 2017

# types of columns of the dataset dataframe
CATEGORICAL_COLS = [
    'common.os',
    'common.loc_provider',
    'time.time',
    'time.week',
    
]

NUMERIC_COLS = [
    # binary
    'personal.cur_rectangle',
    
    # numeric
    'common.loc_accuracy',
    'walk.spherical_dist',
    'walk.spherical_dist_ratio_on_pop',
    'his_heat.absorb_offset'

    # feature engineering
    # "missing_feat", "ps_car_13_x_ps_reg_03",
]

IGNORE_COLS = [
    "id",
    "target",
    'common.city_id',
    'his_heat.weight_on_pos',
    'his_heat.weight_on_link',
    'his_heat.weight_on_route',
    'his_heat.hottest_offset',
    'his_heat.hottest_value',
    'his_heat.nearest_offset',
    'his_heat.nearest_value',
    'his_heat.weight_on_pos_ratio',
    'his_heat.weight_on_link_ratio',
    'his_heat.weight_on_route_ratio',
    'his_heat.pos_link_weight_ratio',
    'his_heat.hottest_offset_ratio',
    'his_heat.hottest_offset_pop_ratio',
    'his_heat.hottest_value_ratio',
    'his_heat.hottest_value_pop_ratio',
    'his_heat.nearest_offset_ratio',
    'his_heat.nearest_offset_pop_ratio',
    'his_heat.nearest_value_ratio',
    'his_heat.nearest_value_pop_ratio',
    'his_heat.nearest_hottest_offset_ratio',
    'his_heat.nearest_hottest_value_ratio',
    'his_heat.hottest_value_offset_ratio',
    'his_heat.nearest_value_offset_ratio',
    'his_heat.hottest_pos_weight_ratio',
    'his_heat.nearest_pos_weight_ratio',
    'heat.link_cluster_point_heat',
    'onsite_30.order_cnt',
    'onsite_30.aboard_offset_median',
    'onsite_30.aboard_onsite_rate_20',
    'onsite_30.aboard_onsite_rate_30',
    'onsite_30.aboard_onsite_rate_40',
    'onsite_30.charge_offset_median',
    'onsite_30.charge_onsite_rate_20',
    'onsite_30.charge_onsite_rate_30',
    'onsite_30.charge_onsite_rate_40',
    'onsite_60.order_cnt',
    'onsite_60.aboard_offset_median',
    'onsite_60.aboard_onsite_rate_20',
    'onsite_60.aboard_onsite_rate_30',
    'onsite_60.aboard_onsite_rate_40',
    'onsite_60.charge_offset_median',
    'onsite_60.charge_onsite_rate_20',
    'onsite_60.charge_onsite_rate_30',
    'onsite_60.charge_onsite_rate_40',
    'onsite_90.order_cnt',
    'onsite_90.aboard_offset_median',
    'onsite_90.aboard_onsite_rate_20',
    'onsite_90.aboard_onsite_rate_30',
    'onsite_90.aboard_onsite_rate_40',
    'onsite_90.charge_offset_median',
    'onsite_90.charge_onsite_rate_20',
    'onsite_90.charge_onsite_rate_30',
    'onsite_90.charge_onsite_rate_40',
    'onsite_180.order_cnt',
    'onsite_180.aboard_offset_median',
    'onsite_180.aboard_onsite_rate_20',
    'onsite_180.aboard_onsite_rate_30',
    'onsite_180.aboard_onsite_rate_40',
    'onsite_180.charge_offset_median',
    'onsite_180.charge_onsite_rate_20',
    'onsite_180.charge_onsite_rate_30',
    'onsite_180.charge_onsite_rate_40',
    'personal.dist_to_cur_center',
    'personal.cur_radius',
    'personal.b4mm_cnt',
    'personal.origin_stat_0',
    'personal.origin_stat_1',
    'personal.origin_stat_from_last_0_0',
    'personal.origin_stat_from_last_0_1',
    'personal.origin_stat_from_last_1_0',
    'personal.origin_stat_from_last_1_1',
    'personal.origin_stat_from_last_2_0',
    'personal.origin_stat_from_last_2_1',
    'personal.origin_stat_from_last_3_0',
    'personal.origin_stat_from_last_3_1',
    'personal.origin_stat_from_now_0_0',
    'personal.origin_stat_from_now_0_1',
    'personal.origin_stat_from_now_1_0',
    'personal.origin_stat_from_now_1_1',
    'personal.origin_stat_from_now_2_0',
    'personal.origin_stat_from_now_2_1',
    'personal.origin_stat_from_now_3_0',
    'personal.origin_stat_from_now_3_1',
    'personal.move_stat_date_diff',
    'personal.move_stat_0',
    'personal.move_stat_1',
    'personal.move_stat_2',
    'personal.move_stat_3',
    'personal.move_stat_from_last_0_0',
    'personal.move_stat_from_last_0_1',
    'personal.move_stat_from_last_0_2',
    'personal.move_stat_from_last_0_3',
    'personal.move_stat_from_last_1_0',
    'personal.move_stat_from_last_1_1',
    'personal.move_stat_from_last_1_2',
    'personal.move_stat_from_last_1_3',
    'personal.move_stat_from_last_2_0',
    'personal.move_stat_from_last_2_1',
    'personal.move_stat_from_last_2_2',
    'personal.move_stat_from_last_2_3',
    'personal.move_stat_from_last_3_0',
    'personal.move_stat_from_last_3_1',
    'personal.move_stat_from_last_3_2',
    'personal.move_stat_from_last_3_3',
    'personal.move_stat_from_now_0_0',
    'personal.move_stat_from_now_0_1',
    'personal.move_stat_from_now_0_2',
    'personal.move_stat_from_now_0_3',
    'personal.move_stat_from_now_1_0',
    'personal.move_stat_from_now_1_1',
    'personal.move_stat_from_now_1_2',
    'personal.move_stat_from_now_1_3',
    'personal.move_stat_from_now_2_0',
    'personal.move_stat_from_now_2_1',
    'personal.move_stat_from_now_2_2',
    'personal.move_stat_from_now_2_3',
    'personal.move_stat_from_now_3_0',
    'personal.move_stat_from_now_3_1',
    'personal.move_stat_from_now_3_2',
    'personal.move_stat_from_now_3_3'
]
